version: '3'

services:
  nginx:
    image: nginx
    container_name: reverse_proxy_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_network
  faqs:
    image: faqs_service
    container_name: faqs_service
    networks:
      - service_faqs_backend
   
networks:
  nginx_network:
    external: true
    name: reverse_proxy__nginx

  service_faqs_backend:
    external: true
    name: service_faqs_backend
